name: GitHub Action

on:
  push:
  pull_request:
    branches-ignore:
      - 'temp*'
      - 'tmp*'
  release:
    types: [ created ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
        # https://endoflife.date/python
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements-test.txt

      - name: Test with pytest
        run: pytest -v -rs tests --runslow

  test-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install .

      - name: Test import
        run: python -c 'import stellar_sdk; print(stellar_sdk.__version__)'